#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

args_count=$#

if [[ args_count -ne 4 ]]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi

file_path=$1
ip=$2
username=$3
ssh_key=$4


scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$ip":~/
