#!/usr/bin/env bash
# Installs Nginx server

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
configs="
server {
	listen 80;
	root /var/www/html/index.nginx-debian.html;
}"
echo "$configs" >> /etc/nginx/nginx.conf
service nginx restart
