#!/usr/bin/env bash
# Installs Nginx server
#Configure Nginx so that its HTTP response contains a custom header

hostname=$(hostname)
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "/http {/a \        add_header X-Served-By \"$hostname\";" /etc/nginx/nginx.conf
sudo service nginx restart
