#!/usr/bin/env bash
#Installs a HAproxy

sudo apt -y update
sudo apt -y install haproxy

configs="
backend web-servers
    balance roundrobin
    server 203580-web-01 52.201.157.19:80
    server 203580-web-02 100.26.230.29:80
"
sudo chown -R $USER:$USER /etc/default/haproxy
sudo chown -R $USER:$USER /etc/haproxy/haproxy.cfg
sudo echo "$configs" >> /etc/haproxy/haproxy.cfg
sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo service haproxy restart
