#!/usr/bin/env bash
#Task 9. Process and PID file

echo $$ > /var/run/myscript.pid

while true; do
	echo "To infinity and beyond"
	trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'rm /var/run/myscript.pid; exit' SIGQUIT
	sleep 2
done
