#!/usr/bin/env bash
#Reads information from /etc/passwd file


while IFS= read -r line; do
	username=$(echo "$line" | cut -d ":" -f 1)
	passwd=$(echo "$line" | cut -d ":" -f 2)
	uid=$(echo "$line" | cut -d ":" -f 3)
	gid=$(echo "$line" | cut -d ":" -f 4)
	info=$(echo "$line" | cut -d ":" -f 5)
	home=$(echo "$line" | cut -d ":" -f 6)
	shell=$(echo "$line" | cut -d ":" -f 7)

	echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $passwd, more info about the user here: $info"
done < /etc/passwd
