#!/usr/bin/env bash
#Modifies the /etc/hosts file

cp /etc/hosts ~/hosts.new
sed -i '/localhost$/s/.*/127.0.0.2	localhost/' ~/hosts.new

if grep -q "facebook.com$" ~/hosts.new; then
	sed -i '/facebook.com$/s/.*/8.8.8.8	facebook.com/' ~/hosts.new
else
	echo "8.8.8.8	facebook.com" >> ~/hosts.new
fi

cp -f ~/hosts.new /etc/hosts
