#!/usr/bin/env bash
#Configure the user of nginx to nginx and listen to port 8080

my_configs="
	listen 8080 default_server;
        listen [::]:8080 default_server ipv6only=on;
"
sudo sed -i '/default_server/d' /etc/nginx/sites-available/default
sudo sed -i '/^server {/r /dev/stdin' /etc/nginx/sites-available/default <<< "$my_configs"
chmod -R 666 /etc/nginx/nginx.conf
pkill -f apache2
sudo service nginx stop
sudo -u nginx service nginx restart
