#!/usr/bin/env bash
#Configure the user of nginx to nginx and listen to port 8080
sed -i s/80/8080/g /etc/nginx/sites-available/default
pkill -f apache2
chmod -R 666 /etc/nginx/nginx.conf
sudo service nginx stop
sudo -u nginx service nginx restart
